---
# tasks file for role-buildifier
- name: Install buildifier
  ansible.builtin.command: "{{ go }} install github.com/bazelbuild/buildtools/buildifier@latest"
  args:
    creates: "{{ ansible_env.HOME }}/go/bin/buildifier"
