---
# tasks file for role-go
- name: Install go
  ansible.builtin.unarchive:
    creates: /usr/local/go/
    dest: /usr/local/
    remote_src: yes
    src: https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz
  become: yes
- name: Export go path
  ansible.builtin.lineinfile:
    line: export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
    path: "{{ ansible_env.HOME }}/.profile"
- name: Set go
  ansible.builtin.set_fact:
    go: /usr/local/go/bin/go
